[2024-08-09 20:02:14,394] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: neo4j_workflow.make_contributor_to_subject_relationships scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2024-08-09 20:02:14,404] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: neo4j_workflow.make_contributor_to_subject_relationships scheduled__2023-01-06T00:00:00+00:00 [queued]>
[2024-08-09 20:02:14,404] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-08-09 20:02:14,404] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-08-09 20:02:14,404] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-08-09 20:02:14,418] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): make_contributor_to_subject_relationships> on 2023-01-06 00:00:00+00:00
[2024-08-09 20:02:14,421] {standard_task_runner.py:52} INFO - Started process 62 to run task
[2024-08-09 20:02:14,424] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'neo4j_workflow', 'make_contributor_to_subject_relationships', 'scheduled__2023-01-06T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/sup_court_graph_workflow.py', '--cfg-path', '/tmp/tmpdsda6ajc', '--error-file', '/tmp/tmp881jh_aj']
[2024-08-09 20:02:14,425] {standard_task_runner.py:80} INFO - Job 8: Subtask make_contributor_to_subject_relationships
[2024-08-09 20:02:14,476] {task_command.py:369} INFO - Running <TaskInstance: neo4j_workflow.make_contributor_to_subject_relationships scheduled__2023-01-06T00:00:00+00:00 [running]> on host 93d118974d3b
[2024-08-09 20:02:14,555] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=neo4j_workflow
AIRFLOW_CTX_TASK_ID=make_contributor_to_subject_relationships
AIRFLOW_CTX_EXECUTION_DATE=2023-01-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-06T00:00:00+00:00
[2024-08-09 20:02:14,556] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sup_court_graph_workflow.py", line 23, in make_contributor_to_subject_relationships
    driver = GraphDatabase.driver(NEO4J_URL, auth=(NEO4J_USER, NEO4J_PASSWORD))
  File "/home/airflow/.local/lib/python3.7/site-packages/neo4j/__init__.py", line 152, in driver
    driver_type, security_type, parsed = parse_neo4j_uri(uri)
  File "/home/airflow/.local/lib/python3.7/site-packages/neo4j/api.py", line 361, in parse_neo4j_uri
    URI_SCHEME_NEO4J_SECURE
neo4j.exceptions.ConfigurationError: URI scheme b'' is not supported. Supported URI schemes are ['bolt', 'bolt+ssc', 'bolt+s', 'neo4j', 'neo4j+ssc', 'neo4j+s']. Examples: bolt://host[:port] or neo4j://host[:port][?routing_context]
[2024-08-09 20:02:14,564] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=neo4j_workflow, task_id=make_contributor_to_subject_relationships, execution_date=20230106T000000, start_date=20240809T200214, end_date=20240809T200214
[2024-08-09 20:02:14,577] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task make_contributor_to_subject_relationships (URI scheme b'' is not supported. Supported URI schemes are ['bolt', 'bolt+ssc', 'bolt+s', 'neo4j', 'neo4j+ssc', 'neo4j+s']. Examples: bolt://host[:port] or neo4j://host[:port][?routing_context]; 62)
[2024-08-09 20:02:14,596] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-08-09 20:02:14,629] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
